### ISSUE TITLE
MateKate on http://cccmz.de/matekate/index.html#map not displaying

### ISSUE THREAD

**Issue by tilmanb** [cccmzwi/matekate#4]
Hi,

the Matekate on http://cccmz.de/matekate/index.html#map is not displaying anything, dies with a JavaScript error

Fehler: OpenLayers.Layer.OSM.Osmarender is not a constructor
Quelldatei: http://cccmz.de/matekate/matekate.html
Zeile: 84

Maybe the OSMARender API changed?

Drink on,
Tilman

**Comment by tilmanb** [comment]
As of march 2012, the Tiles@Home/OSMARender seems to be shutdown, see http://wiki.openstreetmap.org/wiki/OpenLayers#OpenLayers_base_layers_.26_overlays .

**Comment by tokei** [comment]
Thank you for your help! :)
